#!/bin/sh
#  Copyright (C) 2007-2008  CEA/DEN, EDF R&D, OPEN CASCADE
#
#  Copyright (C) 2003-2007  OPEN CASCADE, EADS/CCR, LIP6, CEA/DEN,
#  CEDRAT, EDF R&D, LEG, PRINCIPIA R&D, BUREAU VERITAS
#
#  This library is free software; you can redistribute it and/or
#  modify it under the terms of the GNU Lesser General Public
#  License as published by the Free Software Foundation; either
#  version 2.1 of the License.
#
#  This library is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#  Lesser General Public License for more details.
#
#  You should have received a copy of the GNU Lesser General Public
#  License along with this library; if not, write to the Free Software
#  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307 USA
#
#  See http://www.salome-platform.org/ or email : webmaster.salome@opencascade.com
#
# Tool for updating list of .in file for the SALOME project 
# and regenerating configure script
# It may be called with --with-kernel[=yes,no] or --without-kernel
# option, default is --with-kernel=yes
# Author : Marc Tajchman - CEA
# Date : 10/10/2002
# $Header$
# 14/03/2007: Mikhail PONIKAROV - OCN
# Reorganization for uage of autotools
#
ORIG_DIR=`pwd`
CONF_DIR=`echo $0 | sed -e "s,[^/]*$,,;s,/$,,;s,^$,.,"`

########################################################################
# Check --with-kernel option

MED_WITH_KERNEL="yes"
MED_WITH_GUI="yes"

for option
do
  case $option in
      -with-kernel | --with-kernel)
          MED_WITH_KERNEL="yes"
          MED_WITH_GUI="yes"
          break;;
      -without-kernel | --without-kernel | -with-kernel=no | --with-kernel=no)
          MED_WITH_KERNEL="no"
          MED_WITH_GUI="no"
          break;;
  esac
done

for option
do
  case $option in
      -with-gui | --with-gui)
          MED_WITH_GUI="yes"
          break;;
      -without-gui | --without-gui | -with-gui=no | --with-gui=no)
          MED_WITH_GUI="no"
          break;;
  esac
done

########################################################################
# Test if the KERNEL_ROOT_DIR is set correctly if KERNEL required

if test ${MED_WITH_KERNEL} = yes; then
    if test ! -d "${KERNEL_ROOT_DIR}"; then
        echo "failed : KERNEL_ROOT_DIR variable is not correct !"
        exit
    fi
fi
########################################################################
# Test if the GUI_ROOT_DIR is set correctly if GUI required

if test ${MED_WITH_GUI} = yes; then
    if test ! -d "${GUI_ROOT_DIR}"; then
        echo "failed : GUI_ROOT_DIR variable is not correct !"
        exit
    fi
fi

cd ${CONF_DIR}
ABS_CONF_DIR=`pwd`

#######################################################################
# Update configure.ac script: to set MED_WITH_KERNEL and MED_WITH_GUI variables
chmod +w configure.ac
sed -e s/MED_WITH_KERNEL=[a-z]*/MED_WITH_KERNEL=${MED_WITH_KERNEL}/g configure.ac > configure.tmp
sed -e s/MED_WITH_GUI=[a-z]*/MED_WITH_GUI=${MED_WITH_GUI}/g configure.tmp > configure.ac
rm configure.tmp

# copy configure files
CONFIGURE_SOURCE_DIR=${KERNEL_ROOT_DIR}/salome_adm
if test ${MED_WITH_KERNEL} = no; then
  CONFIGURE_SOURCE_DIR=${ABS_CONF_DIR}/adm_local_without_kernel
fi

rm -rf salome_adm
mkdir -p salome_adm/unix/config_files
#cp -f ${CONFIGURE_SOURCE_DIR}/unix/config_files/* salome_adm/unix/config_files
cp -f ${CONFIGURE_SOURCE_DIR}/unix/SALOMEconfig.h.in salome_adm/unix
#if test ${MED_WITH_KERNEL} = yes; then
#  cp -f ${CONFIGURE_SOURCE_DIR}/unix/pythonbe.py salome_adm/unix
#fi

# if with GUI, cofy configure files from it
#if test ${MED_WITH_GUI} = yes; then
#  cp -f ${GUI_ROOT_DIR}/adm_local/unix/config_files/* salome_adm/unix/config_files
#fi

# remove KERNEL deprecated configure files
#for deprecated in ac_cc_warnings.m4 ac_cxx_partial_specialization.m4 \
#  check_mico.m4 config.guess ltmain.sh ac_cxx_bool.m4 ltconfig ac_cxx_typename.m4 \
#  check_pthreads.m4 config.sub libtool.m4 ac_cxx_mutable.m4 missing
#do
#  rm -f salome_adm/unix/config_files/${deprecated}
#done

# ____________________________________________________________________
# aclocal creates the aclocal.m4 file from the standard macro and the
# custom macro embedded in the directory salome_adm/unix/config_files
# and KERNEL config_files directory.
# output:
#   aclocal.m4
#   autom4te.cache (directory)
echo "====================================================== aclocal"

if test ${MED_WITH_GUI} = yes; then
  aclocal -I adm_local/unix/config_files \
          -I ${CONFIGURE_SOURCE_DIR}/unix/config_files \
	  -I ${GUI_ROOT_DIR}/adm_local/unix/config_files || exit 1
else
  aclocal -I adm_local/unix/config_files \
          -I ${CONFIGURE_SOURCE_DIR}/unix/config_files || exit 1
fi

# ____________________________________________________________________
# libtoolize creates some configuration files (ltmain.sh,
# config.guess and config.sub). It only depends on the libtool
# version. The files are created in the directory specified with the
# AC_CONFIG_AUX_DIR(<mydir>) tag (see configure.ac).
# output:
#   salome_adm/unix/config_files/config.guess
#   salome_adm/unix/config_files/config.sub
#   salome_adm/unix/config_files/ltmain.sh
#echo "====================================================== libtoolize"

libtoolize --force --copy --automake || exit 1

# ____________________________________________________________________
# make link to KERNEL configuration files to
#ln -sf ${KERNEL_ROOT_DIR}/salome_adm .

# ____________________________________________________________________
# autoconf creates the configure script from the file configure.ac (or
# configure.in if configure.ac doesn't exist)
# output:
#   configure
echo "====================================================== autoconf"

autoconf

# ____________________________________________________________________
# automake creates some scripts used in building process
# (install-sh, missing, ...). It only depends on the automake
# version. The files are created in the directory specified with the
# AC_CONFIG_AUX_DIR(<mydir>) tag (see configure.ac). This step also
# creates the Makefile.in files from the Makefile.am files.
# output:
#   salome_adm/unix/config_files/compile
#   salome_adm/unix/config_files/depcomp
#   salome_adm/unix/config_files/install-sh
#   salome_adm/unix/config_files/missing
#   salome_adm/unix/config_files/py-compile
#   Makefile.in (from Makefile.am)
echo "====================================================== automake"

automake --copy --gnu --add-missing --warnings=no-portability
