#! /bin/sh -f

outdir="/tmp"
if test "z$TMP" != "z" && test -e $TMP; then
    outdir=$TMP
else
 if test "z$TMPDIR" != "z" && test -e $TMPDIR; then
    outdir=$TMPDIR
 fi
fi

infile=${srcdir}/../../resources/pointe.med

outfile=./pointe.med2.3

./med2_1_To_med2_2 $infile

ok=$?

rm $outfile

exit  $ok
