#! /bin/sh -f

outdir="/tmp"
if test "z$TMP" != "z" && test -e $TMP; then
    outdir=$TMP
else
 if test "z$TMPDIR" != "z" && test -e $TMPDIR; then
    outdir=$TMPDIR
 fi
fi

infile=${srcdir}/../../resources/BoxTetra2.med

outfile=$outdir/convertToPoly_BoxTetra2.med

./convertToPoly $infile $outfile BoxTetra2

ok=$?

rm $outfile

exit $ok