#! /bin/sh -f

outdir="/tmp"
if test "z$TMP" != "z" && test -e $TMP; then
    outdir=$TMP
else
 if test "z$TMPDIR" != "z" && test -e $TMPDIR; then
    outdir=$TMPDIR
 fi
fi

initfile=${srcdir}/../../resources/zzzz121b_without_tr6.med
infile=test_profil_MedFieldDriver.med

curdir=`pwd`
cd $outdir
cp $initfile ./$infile

$curdir/test_profil_MedFieldDriver $infile RESUZERODEPL____________________ 1 1

ok=$?

rm $infile
rm Copy_withmesh_test_profil_MedFieldDriver.med
rm Copy_nomesh_test_profil_MedFieldDriver.med

exit $ok
