#! /bin/sh -f

outdir="/tmp"
if test "z$TMP" != "z" && test -e $TMP; then
    outdir=$TMP
else
 if test "z$TMPDIR" != "z" && test -e $TMPDIR; then
    outdir=$TMPDIR
 fi
fi

infile=${srcdir}/../../resources/poly3D.med

./test_MEDMEM_poly3D $infile poly3D

exit

