#! /bin/sh -f

outdir="/tmp"
if test "z$TMP" != "z" && test -e $TMP; then
    outdir=$TMP
else
 if test "z$TMPDIR" != "z" && test -e $TMPDIR; then
    outdir=$TMPDIR
 fi
fi

initfile=${srcdir}/../../resources/TimeStamps.med
infile=$outdir/testAnalFile.med

cp $initfile $infile

./testAnalFile $infile

ok=$?

\rm -f $infile
\rm -f $outdir/testAnalFileAnal_V21.med
\rm -f $outdir/testAnalFileAnal_V22.med

exit $ok
