#! /bin/sh -f

outdir="/tmp"
if test "z$TMP" != "z" && test -e $TMP; then
    outdir=$TMP
else
 if test "z$TMPDIR" != "z" && test -e $TMPDIR; then
    outdir=$TMPDIR
 fi
fi

infile=${srcdir}/../../resources/blow5_ascii.case

outfile=${outdir}/ensight2med.med

./ensight2med $infile $outfile

ok=$?

rm $outfile

exit $ok