#! /bin/sh -f

outdir="/tmp"
if test "z$TMP" != "z" && test -e $TMP; then
    outdir=$TMP
else
 if test "z$TMPDIR" != "z" && test -e $TMPDIR; then
    outdir=$TMPDIR
 fi
fi

infile=${srcdir}/../../resources/pointe.med

outfile=$outdir/pointe.vtk

./med2vtk $infile $outfile

ok=$?

rm $outfile

exit $ok
