#! /bin/sh -f

outdir="/tmp"
if test "z$TMP" != "z" && test -e $TMP; then
    outdir=$TMP
else
 if test "z$TMPDIR" != "z" && test -e $TMPDIR; then
    outdir=$TMPDIR
 fi
fi

infile=${srcdir}/../../resources/pointe_import22.med

./test_operation_fielddouble $infile maa1 fieldcelldoublescalar

exit

