#! /bin/sh -f
# Copyright (C) 2007-2012  CEA/DEN, EDF R&D, OPEN CASCADE
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307 USA
#
# See http://www.salome-platform.org/ or email : webmaster.salome@opencascade.com
#

outdir="/tmp"
if test "z$TMP" != "z" && test -e $TMP; then
    outdir=$TMP
else
 if test "z$TMPDIR" != "z" && test -e $TMPDIR; then
    outdir=$TMPDIR
 fi
fi

# make med file containing int field on cells from ensight file

infile=${srcdir}/../../resources/blow5_ascii.case
outfile=${outdir}/test_operation_fieldint.med

./ensight2med $infile $outfile I > /dev/null 2>&1

# main test
./test_operation_fieldint $outfile EnsightMesh displacement_c  > /dev/null 2>&1

ok=$?

echo $outfile
rm $outfile

exit $ok
