#! /bin/sh -f

outdir="/tmp"
if test "z$TMP" != "z" && test -e $TMP; then
    outdir=$TMP
else
 if test "z$TMPDIR" != "z" && test -e $TMPDIR; then
    outdir=$TMPDIR
 fi
fi

initfile=${srcdir}/../../resources/zzzz121b_without_tr6.med
infile=test_profil_gauss_MedFieldDriver.med

curdir=`pwd`
cp $initfile $outdir/$infile
cd $outdir

$curdir/test_profil_gauss_MedFieldDriver $infile RESUZEROSIEF_ELGA_DEPL__________ 1 1

ok=$?

\rm -f $infile
\rm -f Copy_withmesh_test_profil_gauss_MedFieldDriver.med
\rm -f Copy_nomesh_test_profil_gauss_MedFieldDriver.med

exit $ok
