#ifndef _TESTMEDCLIENT_GEN_IDL_
#define _TESTMEDCLIENT_GEN_IDL_

#include "SALOME_Exception.idl"
#include "SALOME_Component.idl"
#include "SALOMEDS.idl"
#include "MED.idl"

module SALOME_TESTMEDCLIENT
{
  interface TESTMEDCLIENT_Gen : Engines::Component
  {
    void go(in SALOME_MED::MED objMed);
    void go2(in SALOME_MED::MED objMed);
  };
};

#endif
