#!/usr/bin/env python
# --
# Copyright (C) 2009-2010 CEA DEN
# Author : Erwan ADAM (CEA)
# --

from sys import argv
d = argv[0]
from os.path import dirname
d = dirname(d)
from os.path import abspath
d = abspath(d+'/../lib')
from sys import path
if d not in path:
    path.insert(0, d)
    pass

from medutilities import sauv2med
from sys import argv
sauv2med(*argv[1:])
