<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS>
  <context>
    <name>@default</name>
    <message>
      <source>MED_BUT_OK</source>
      <translation>OK</translation>
    </message>
    <message>
      <source>MED_INF_FIELDNAME</source>
      <translation>読み取りするフィールドの名前を指定して下さい</translation>
    </message>
    <message>
      <source>MED_INF_MESHNAME</source>
      <translation>読み取りするメッシュの名前を指定して下さい</translation>
    </message>
    <message>
      <source>MED_INF_NOIOR</source>
      <translation>オブジェクトは、IOR を持たない</translation>
    </message>
    <message>
      <source>MED_INF_NOTIMPL</source>
      <translation>このオブジェクトは実装されない</translation>
    </message>
    <message>
      <source>MED_WRN_WARNING</source>
      <translation>警告</translation>
    </message>
    <message>
      <source>MEN_SHOW</source>
      <translation>表示</translation>
    </message>
    <message>
      <source>MEN_DUMPMESH</source>
      <translation>メッシュリスト</translation>
    </message>
    <message>
      <source>MEN_DUMPSUBMESH</source>
      <translation>サブメッシュリスト</translation>
    </message>
    <message>
      <source>MEN_HIDE</source>
      <translation>非表示</translation>
    </message>
    <message>
      <source>MEN_EXPLORE</source>
      <translation>MED ファイルを探索</translation>
    </message>
    <message>
      <source>MEN_FIELDSEL</source>
      <translation>フィールドの選択</translation>
    </message>
    <message>
      <source>MEN_MESHSEL</source>
      <translation>メッシュの選択</translation>
    </message>
    <message>
      <source>MEN_POPUPTEST</source>
      <translation>ポップアップテスト</translation>
    </message>
    <message>
      <source>STB_SHOW</source>
      <translation>表示</translation>
    </message>
    <message>
      <source>STB_DUMPMESH</source>
      <translation>メッシュリスト</translation>
    </message>
    <message>
      <source>STB_DUMPSUBMESH</source>
      <translation>メッシュリスト</translation>
    </message>
    <message>
      <source>STB_HIDE</source>
      <translation>非表示</translation>
    </message>
    <message>
      <source>STB_EXPLORE</source>
      <translation>MED ファイルを探索</translation>
    </message>
    <message>
      <source>STB_FIELDSEL</source>
      <translation>フィールドを読み取り</translation>
    </message>
    <message>
      <source>STB_MESHSEL</source>
      <translation>メッシュ読み込み</translation>
    </message>
    <message>
      <source>STB_POPUPTEST</source>
      <translation>ポップアップテスト</translation>
    </message>
    <message>
      <source>TB_MED</source>
      <translation>MED ツールバー</translation>
    </message>
    <message>
      <source>TOP_SHOW</source>
      <translation>表示</translation>
    </message>
    <message>
      <source>TOP_DUMPMESH</source>
      <translation>メッシュリスト</translation>
    </message>
    <message>
      <source>TOP_DUMPSUBMESH</source>
      <translation>サブメッシュリスト</translation>
    </message>
    <message>
      <source>TOP_HIDE</source>
      <translation>非表示</translation>
    </message>
    <message>
      <source>TOP_EXPLORE</source>
      <translation>MED ファイルを探索</translation>
    </message>
    <message>
      <source>TOP_FIELDSEL</source>
      <translation>フィールドの選択</translation>
    </message>
    <message>
      <source>TOP_MESHSEL</source>
      <translation>メッシュの選択</translation>
    </message>
    <message>
      <source>TOP_POPUPTEST</source>
      <translation>ポップアップテスト</translation>
    </message>
  </context>
</TS>
