<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.0" language="en_US">
  <context>
    <name>@default</name>
    <message>
      <source>ICO_IMPORT_MED</source>
      <translation>datasource_add.png</translation>
    </message>
    <message>
      <source>ICO_DATASOURCE</source>
      <translation>datasource.png</translation>
    </message>
    <message>
      <source>ICO_DATASOURCE_ADD</source>
      <translation>datasource_add.png</translation>
    </message>
    <message>
      <source>ICO_PROCESSING_CHANGE_MESH</source>
      <translation>processing_changeUnderlyingMesh.png</translation>
    </message>
    <message>
      <source>ICO_PROCESSING_INTERPOLATE_FIELD</source>
      <translation>processing_interpolateField.png</translation>
    </message>
    <message>
      <source>ICO_DATASOURCE_EXPAND_FIELD</source>
      <translation>datasource_expandfield.png</translation>
    </message>
    <message>
      <source>ICO_DATASOURCE_FIELD</source>
      <translation>datasource_field.png</translation>
    </message>
    <message>
      <source>ICO_DATASOURCE_MESH</source>
      <translation>datasource_mesh.png</translation>
    </message>
    <message>
      <source>ICO_DATASOURCE_USE</source>
      <translation>datasource_use.png</translation>
    </message>
    <message>
      <source>ICO_FOLDER</source>
      <translation>folder.png</translation>
    </message>
    <message>
      <source>ICO_IMAGE_ADD</source>
      <translation>image_add.png</translation>
    </message>
    <message>
      <source>ICO_MED</source>
      <translation>MEDCalc.png</translation>
    </message>
    <message>
      <source>ICO_MED_SMALL</source>
      <translation>MEDCalc_small.png</translation>
    </message>
    <message>
      <source>ICO_WORKSPACE_CLEAN</source>
      <translation>workspace_clean.png</translation>
    </message>
    <message>
      <source>ICO_WORKSPACE_SAVE</source>
      <translation>workspace_save.png</translation>
    </message>
    <message>
      <source>ICO_ICO_DELETE_PRESENTATION</source>
      <translation>delete.png</translation>
    </message>
    <!-- Presentation toolbar icons (default theme)-->
    <message>
      <source>ICO_PRESENTATION_MESH_VIEW_DEFAULT</source>
      <translation>mesh24.png</translation>
    </message>    
    <message>
      <source>ICO_PRESENTATION_SCALAR_MAP_DEFAULT</source>
      <translation>scalarmap24.png</translation>
    </message>
    <message>
      <source>ICO_PRESENTATION_CONTOUR_DEFAULT</source>
      <translation>pqIsosurface24.png</translation>
    </message>
    <message>
      <source>ICO_PRESENTATION_VECTOR_FIELD_DEFAULT</source>
      <translation>pqGlyph24.png</translation>
    </message>
    <message>
      <source>ICO_PRESENTATION_SLICES_DEFAULT</source>
      <translation>pqSlice24.png</translation>
    </message>
    <message>
      <source>ICO_PRESENTATION_DEFLECTION_SHAPE_DEFAULT</source>
      <translation>pqWarp24.png</translation>
    </message>
    <message>
      <source>ICO_PRESENTATION_POINT_SPRITE_DEFAULT</source>
      <translation>pqNodeMapData24.png</translation>
    </message>
    <!-- Presentation tree icons (default theme)-->
    <message>
      <source>ICO_MEDPresentationMeshView_DEFAULT</source>
      <translation>mesh16.png</translation>
    </message>    
    <message>
      <source>ICO_MEDPresentationScalarMap_DEFAULT</source>
      <translation>scalarmap16.png</translation>
    </message>
    <message>
      <source>ICO_MEDPresentationContour_DEFAULT</source>
      <translation>pqIsosurface16.png</translation>
    </message>
    <message>
      <source>ICO_MEDPresentationVectorField_DEFAULT</source>
      <translation>pqGlyph16.png</translation>
    </message>
    <message>
      <source>ICO_MEDPresentationSlices_DEFAULT</source>
      <translation>pqSlice16.png</translation>
    </message>
    <message>
      <source>ICO_MEDPresentationDeflectionShape_DEFAULT</source>
      <translation>pqWarp16.png</translation>
    </message>
    <message>
      <source>ICO_MEDPresentationPointSprite_DEFAULT</source>
      <translation>pqNodeMapData16.png</translation>
    </message>
    <!-- Presentation toolbar icons (modern theme)-->
    <message>
      <source>ICO_PRESENTATION_MESH_VIEW_MODERN</source>
      <translation>mesh24.png</translation>
    </message>    
    <message>
      <source>ICO_PRESENTATION_SCALAR_MAP_MODERN</source>
      <translation>scalarmap24.png</translation>
    </message>
    <message>
      <source>ICO_PRESENTATION_CONTOUR_MODERN</source>
      <translation>pqIsosurface24.png</translation>
    </message>
    <message>
      <source>ICO_PRESENTATION_VECTOR_FIELD_MODERN</source>
      <translation>pqGlyph24.png</translation>
    </message>
    <message>
      <source>ICO_PRESENTATION_SLICES_MODERN</source>
      <translation>pqSlice24.png</translation>
    </message>
    <message>
      <source>ICO_PRESENTATION_DEFLECTION_SHAPE_MODERN</source>
      <translation>pqWarp24.png</translation>
    </message>
    <message>
      <source>ICO_PRESENTATION_POINT_SPRITE_MODERN</source>
      <translation>pqNodeMapData24.png</translation>
    </message>
    <!-- Presentation tree icons (modern theme)-->
    <message>
      <source>ICO_MEDPresentationMeshView_MODERN</source>
      <translation>mesh16.png</translation>
    </message>    
    <message>
      <source>ICO_MEDPresentationScalarMap_MODERN</source>
      <translation>scalarmap16.png</translation>
    </message>
    <message>
      <source>ICO_MEDPresentationContour_MODERN</source>
      <translation>pqIsosurface16.png</translation>
    </message>
    <message>
      <source>ICO_MEDPresentationVectorField_MODERN</source>
      <translation>pqGlyph16.png</translation>
    </message>
    <message>
      <source>ICO_MEDPresentationSlices_MODERN</source>
      <translation>pqSlice16.png</translation>
    </message>
    <message>
      <source>ICO_MEDPresentationDeflectionShape_MODERN</source>
      <translation>pqWarp16.png</translation>
    </message>
    <message>
      <source>ICO_MEDPresentationPointSprite_MODERN</source>
      <translation>pqNodeMapData16.png</translation>
    </message>
    <!-- Presentation toolbar icons (classic theme)-->
    <message>
      <source>ICO_PRESENTATION_MESH_VIEW_CLASSIC</source>
      <translation>visu_mesh24.png</translation>
    </message>    
    <message>
      <source>ICO_PRESENTATION_SCALAR_MAP_CLASSIC</source>
      <translation>visu_scalars24.png</translation>
    </message>
    <message>
      <source>ICO_PRESENTATION_CONTOUR_CLASSIC</source>
      <translation>visu_isosurfaces24.png</translation>
    </message>
    <message>
      <source>ICO_PRESENTATION_VECTOR_FIELD_CLASSIC</source>
      <translation>visu_vectors24.png</translation>
    </message>
    <message>
      <source>ICO_PRESENTATION_SLICES_CLASSIC</source>
      <translation>visu_cutplanes24.png</translation>
    </message>
    <message>
      <source>ICO_PRESENTATION_DEFLECTION_SHAPE_CLASSIC</source>
      <translation>visu_deformed24.png</translation>
    </message>
    <message>
      <source>ICO_PRESENTATION_POINT_SPRITE_CLASSIC</source>
      <translation>visu_points24.png</translation>
    </message>
    <!-- Presentation tree icons (classic theme)-->
    <message>
      <source>ICO_MEDPresentationMeshView_CLASSIC</source>
      <translation>visu_mesh16.png</translation>
    </message>
    <message>
      <source>ICO_MEDPresentationScalarMap_CLASSIC</source>
      <translation>visu_scalars16.png</translation>
    </message>
    <message>
      <source>ICO_MEDPresentationContour_CLASSIC</source>
      <translation>visu_isosurfaces16.png</translation>
    </message>
    <message>
      <source>ICO_MEDPresentationVectorField_CLASSIC</source>
      <translation>visu_vectors16.png</translation>
    </message>
    <message>
      <source>ICO_MEDPresentationSlices_CLASSIC</source>
      <translation>visu_cutplanes16.png</translation>
    </message>
    <message>
      <source>ICO_MEDPresentationDeflectionShape_CLASSIC</source>
      <translation>visu_deformed16.png</translation>
    </message>
    <message>
      <source>ICO_MEDPresentationPointSprite_CLASSIC</source>
      <translation>visu_points16.png</translation>
    </message>
    <message>
      <source>ICO_DELETE_PRESENTATION</source>
      <translation>close.png</translation>
    </message>
  </context>
</TS>
