<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.0" language="en_US">
  <context>
    <name>@default</name>
    <message>
      <source>ICO_IMPORT_MED</source>
      <translation>datasource_add.png</translation>
    </message>
    <message>
      <source>ICO_DATASOURCE</source>
      <translation>datasource.png</translation>
    </message>
    <message>
      <source>ICO_DATASOURCE_ADD</source>
      <translation>datasource_add.png</translation>
    </message>
    <message>
      <source>ICO_DATASOURCE_CHANGE_MESH</source>
      <translation>datasource_changeUnderlyingMesh.png</translation>
    </message>
    <message>
      <source>ICO_DATASOURCE_INTERPOLATE_FIELD</source>
      <translation>datasource_interpolateField.png</translation>
    </message>
    <message>
      <source>ICO_DATASOURCE_EXPAND_FIELD</source>
      <translation>datasource_expandfield.png</translation>
    </message>
    <message>
      <source>ICO_DATASOURCE_FIELD</source>
      <translation>datasource_field.png</translation>
    </message>
    <message>
      <source>ICO_DATASOURCE_MESH</source>
      <translation>datasource_mesh.png</translation>
    </message>
    <message>
      <source>ICO_DATASOURCE_USE</source>
      <translation>datasource_use.png</translation>
    </message>
    <message>
      <source>ICO_DATASOURCE_VIEW</source>
      <translation>datasource_view.png</translation>
    </message>
    <message>
      <source>ICO_FOLDER</source>
      <translation>folder.png</translation>
    </message>
    <message>
      <source>ICO_IMAGE_ADD</source>
      <translation>image_add.png</translation>
    </message>
    <message>
      <source>ICO_MED</source>
      <translation>MEDCalc.png</translation>
    </message>
    <message>
      <source>ICO_MED_SMALL</source>
      <translation>MEDCalc_small.png</translation>
    </message>
    <message>
      <source>ICO_WORKSPACE_CLEAN</source>
      <translation>workspace_clean.png</translation>
    </message>
    <message>
      <source>ICO_WORKSPACE_SAVE</source>
      <translation>workspace_save.png</translation>
    </message>
  </context>
</TS>
