######################################################################
# Automatically generated by qmake (2.01a) mer. oct. 6 14:46:48 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += . ../dialogs

# Input
HEADERS += ../dialogs/DlgAlias.h
FORMS += ../dialogs/dlgAlias.ui
SOURCES += ../dialogs/DlgAlias.cxx ../dialogs/dlgTester.cxx
