//=============================================================================
// File      : Med_Gen.idl
// Project   : SALOME
// Copyright : EDF 2001
//=============================================================================

#ifndef _Med_GEN_IDL_
#define _Med_GEN_IDL_


#include "SALOME_Exception.idl"
#include "SALOME_Component.idl"
#include "SALOMEDS.idl"
#include "MED.idl"

module SALOME_MED
{
  interface MED_Gen : Engines::Component, SALOMEDS::Driver
  {
	SALOME_MED::MESH readMeshInFile(in string fileName,
					in string studyName,
					in string meshName )
					raises (SALOME::SALOME_Exception);
	SALOME_MED::FIELD readFieldInFile(in string fileName,
					in string studyName,
					in string fieldName,
					in long ordre,
					in long iter )
					raises (SALOME::SALOME_Exception);
	SALOME_MED::MED readStructFile(in string fileName,
					in string studyName )
					raises (SALOME::SALOME_Exception);

        void readStructFileWithFieldType(in string fileName,
					 in string studyName )
	  raises (SALOME::SALOME_Exception);
  };

};

#endif
