//=============================================================================
// File      : SALOME_Session.idl
// Created   : mar jun 19 09:15:07 CEST 2001
// Author    : Paul RASCLE, EDF
// Project   : SALOME
// Copyright : EDF 2001
// $Header$
//=============================================================================

//! module SALOME regroups all idl definitions for SALOME Kernel
#include "VISU_Gen.idl"
module SALOME
{
  enum SessionState {asleep, running } ;

  //! Session State and Statistics
  /*!
   *  Field list
   *   - state
   *     -# asleep  : no running study
   *     -# running : one or more running studies
   *   - number of running studies
   *   - active GUI : true/false
   */
   
  struct StatSession
  {
    SessionState state ; 
    short        runningStudies ;
    boolean      activeGUI ;
  } ;

  /*!
   * Session Server launches and stops GUI (Graphical User Interface)
   * Session can be active without GUI (one or more running studies)
   */

  interface Session
  {
    exception GUIActive {} ;
    exception RunningStudies {} ;  

    //! Launches GUI
    oneway void GetInterface() ; 
    VISU::VISU_Gen GetVisuGen();

    //! Stops Session (must be idle)
    void StopSession() raises(GUIActive, RunningStudies) ;

    //! Gets Session State
    StatSession GetStatSession() ;

    void ping();
  } ;

} ;
